### PR TITLE
Version 37

### LINKED ISSUE #132: Add a link to Bing?
Hello,
is it possible to add a link to Bing in the extension menu? Ideally it would redirect to the page of the current day, for example: https://www.bing.com/search?q=chocolate+hills+bohol&form=hpcapt&filters=HpDate:%2220211123_2300%22

It could also lead to Bing's homepage https://www.bing.com/ because it contains the link that present the photo of the day.

### LINKED ISSUE #134: [BUG] Cleaning up old images doesn't seem to work as expected (if at all)
>NOTE:
>GNOME will sometimes report errors associated extensions if you manually update them via the extensions website. These errors can be resolved by restarting GNOME shell (logging out and then back in again). If it's still creating errors, then please go ahead create an issue.

**Describe the bug**

**Screenshots**
Clicking toggle in doesn't clean up old images in order of age, rather it only deletes last selected images if at all

**Desktop (please complete the following information):**
 - OS: various
 - Extension Version: 36, probably earlier
 - GNOME Version: 40.x

**Additional context**
Relates to migration to change to image history. Full Bing JSON data history is stored locally, but this isn't being used to identify the oldest images. As we only store the default history (typically 7 days), images older than that won't be deleted if the switch is toggled, and images will be deleted in a strange order if the user select images through the menu or carousel.

### LINKED ISSUE #135: [BUG] Hide/Unhide indicator toggle only works after log out/reboot
Hi. Thanks for a really nice extension!

**Describe the bug**
Just wanted to note that changing the state of the "Hide the indicator" setting only take effect after logging out and back in again. Not sure if this is a bug or intended, but I know other extensions are able to turn the indicator on and off instantly, and if it is intended it would be nice if it said "(needs reboot)" or something, so it's not as confusing.

Thanks! :)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - Extension Version: It doesn't say which version on the About page for the extension settings, but it says it's a hotfix for v 35, so I'm guessing it's 36
 - GNOME Version: 40.4

**Additional context**
Using Gnome-session

### PR DESCRIPTION
**Pull request by neffo**
Changes in this version:
- [x] remove obsolete switches in prefs
- [x] fix build instructions
- [x] move to arrow functions, fix #132 
- [x] fix indicator hide toggle, fix #135 
- [x] fix image clean up to use full image list (was problematic if toggled) fix #134 
- [x] fix notifications not triggering
- [x] add info and view buttons to gallery
- [x] don't generate thumbnails if not keeping images
- [x] Update German Translation #137 
- [x] Import and export Bing JSON data #136
- [x] fix caption in the top-right menu being truncated #138
- [x] don't force background zoom style, add preferences for background style #38 
- [x] fix try icon switching
- [x] code clean up
- [x] test on GNOME 3.36
- [x] test on GNOME 3.38
- [x] test on GNOME 40
- [x] test on GNOME 41
- [x] remove debug state
- [x] bump metadata, update readme

### CODE REVIEW

File: extension.js [hunk 1]
```diff
@@ -334,7 +334,7 @@ class BingWallpaperIndicator extends PanelMenu.Button {
         clutter_text.set_line_wrap(true);
         clutter_text.set_ellipsize(0);
         clutter_text.set_max_length(0);
-        menuItem.label.set_style("max-width: 480px;");
+        menuItem.label.set_style("max-width: 420px;");
```
Comment (bdaase) [inline extension.js:337]: It's a bit weird that this fixes the issue but I'll take it ;)

Comment (neffo) [reply extension.js:337]: GNOME gonna GNOME.
